### ISSUE TITLE
Copying a list

### ISSUE THREAD

**Issue by coralvanda** [st4rgut25/Battleshiph-Game#3]
I saw that you were trying to make a copy of a list with either `list()` or `copy.copy()`, but it sounds like it didn't work.  What list were you trying to copy, and what did you need to do with the copy while preserving the original list?

I only see `list()` used on line 93, and I'm pretty sure that isn't what you were talking about.

**Comment by st4rgut25** [comment]
hey coralvanda, i finally figured out how to copy nested list called newgame. I used copy.deepcopy() to copy the nested array. Thanks for looking over my code

**Comment by coralvanda** [comment]
Sounds good.  Now you should be able to update the code with your new commit, and close this issue.  If that's the only thing you were having trouble with, then you're done.  Otherwise, make a post for a new issue and let's take a look at it.
